"use client";

import React, { useEffect, useState } from "react";
import ComponentCard from "@/components/common/ComponentCard";
import Label from "@/components/form/Label";
import Input from "@/components/form/input/InputField";
import DatePicker from "@/components/form/date-picker";
import useProfile from "@/hooks/useProfile";
import { supabase } from "@/lib/supabase/supabaseClient";

type RequestProps = {
    value: any;
    onChange: (val: any) => void;
    refreshTrigger?: number;
};

export default function RequestInputs({ value, onChange, refreshTrigger = 0 }: RequestProps) {
    const { profile } = useProfile();
    const [previewCode, setPreviewCode] = useState("Generating...");

    useEffect(() => {
        if (!profile?.department?.deptcode) return;

        const generatePreviewCode = async () => {
            const now = new Date();
            const yy = String(now.getFullYear()).slice(-2);
            const mm = String(now.getMonth() + 1).padStart(2, "0");
            const yymm = `${yy}${mm}`;
            const deptcode = profile.department.deptcode;

            const { count } = await supabase
                .from("requests")
                .select("*", { count: "exact", head: true })
                .ilike("requestcode", `REQ-${yymm}-${deptcode}-%`);

            const nextSeq = String((count ?? 0) + 1).padStart(4, "0");
            setPreviewCode(`REQ-${yymm}-${deptcode}-${nextSeq}`);
        };

        generatePreviewCode();
    // refreshTrigger increments after each submit to re-query the latest count
    }, [profile?.department?.deptcode, refreshTrigger]);

    const handleChange = (field: string, fieldValue: any) => {
        onChange({
            ...value,
            [field]: fieldValue,
        });
    };


    return (
        <ComponentCard
            title="Create new promotion request"
            desc="Please fill out the form below to create a new promotion request."
        >
            <div className="space-y-6">

                {/* REQUEST CODE */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <Label>Request-code</Label>
                        <Input
                            type="text"
                            disabled
                            value={previewCode}
                            hint="Auto-generated by system"
                        />
                    </div>

                    <div>
                        <Label>Date created</Label>
                        <Input
                            type="date"
                            disabled
                            value={new Date().toLocaleDateString("sv-SE", { timeZone: "Asia/Ho_Chi_Minh" })}
                        />
                    </div>
                </div>

                {/* PROMOTION NAME */}
                <div>
                    <Label>Promotion name</Label>
                    <Input
                        placeholder="Enter promotion name"
                        value={value?.promotionname || ""}
                        onChange={(e) => handleChange("promotionname", e.target.value)}
                    />
                </div>

                {/* DATE */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4">
                    <div>
                        <DatePicker
                            id="start-date"
                            label="Start date"
                            placeholder="Select a date"
                            onChange={(_dates, dateStr) => handleChange("startdate", dateStr)}
                        />
                    </div>

                    <div>
                        <DatePicker
                            id="end-date"
                            label="End date"
                            placeholder="Select a date"
                            onChange={(_dates, dateStr) => handleChange("enddate", dateStr)}
                        />
                    </div>
                </div>

                {/* REQUESTER + DEPARTMENT */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pb-4">
                    <div>
                        <Label>Requester</Label>
                        <input // Requester ID (hidden, for DB)
                            hidden
                            type="text"
                            placeholder="Enter user ID"
                            value={profile?.user_id}
                            onChange={(e) => handleChange("requester", e.target.value)}
                        />
                        <Input
                            type="text"
                            placeholder="Enter name"
                            value={profile?.fullname}
                            disabled
                            onChange={(e) => handleChange("requester", e.target.value)}
                        />
                    </div>

                    <div>
                        <Label>Department</Label>
                        <Input
                            type="text"
                            placeholder="Enter name"
                            value={profile?.department.deptname || ""}
                            disabled
                            onChange={(e) => handleChange("department", e.target.value)}
                        />
                        <input // Requester ID (hidden, for DB)
                            hidden
                            type="text"
                            placeholder="Enter user ID"
                            value={profile?.department.id || ""}
                            onChange={(e) => handleChange("requester", e.target.value)}
                        />
                    </div>
                </div>

            </div>
        </ComponentCard>
    );
}